USE BDP1_SEMI2;
DROP TABLE IF EXISTS venta;
DROP TABLE IF EXISTS empleado;
DROP TABLE IF EXISTS entrega;
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS time_line;
DROP TABLE IF EXISTS temporal;
